// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANHYt0mrm4rwv5EGPcUVzk1vaBMsVi1RA',
    appId: '1:701854077758:web:2ee1f4a5297b456a52926f',
    messagingSenderId: '701854077758',
    projectId: 'repasoflutterjunio',
    authDomain: 'repasoflutterjunio.firebaseapp.com',
    storageBucket: 'repasoflutterjunio.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD75UlTH1VbFm3DsJYiz9bK6DLTZbrBQTI',
    appId: '1:701854077758:android:2d94587698167f5052926f',
    messagingSenderId: '701854077758',
    projectId: 'repasoflutterjunio',
    storageBucket: 'repasoflutterjunio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb25DMhT1JBPeW-JXczgfw16TpnMyuOUU',
    appId: '1:701854077758:ios:8a752b66fc05f22752926f',
    messagingSenderId: '701854077758',
    projectId: 'repasoflutterjunio',
    storageBucket: 'repasoflutterjunio.firebasestorage.app',
    iosBundleId: 'com.example.repasoExamen2Flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb25DMhT1JBPeW-JXczgfw16TpnMyuOUU',
    appId: '1:701854077758:ios:8a752b66fc05f22752926f',
    messagingSenderId: '701854077758',
    projectId: 'repasoflutterjunio',
    storageBucket: 'repasoflutterjunio.firebasestorage.app',
    iosBundleId: 'com.example.repasoExamen2Flutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANHYt0mrm4rwv5EGPcUVzk1vaBMsVi1RA',
    appId: '1:701854077758:web:bae98bd0b9246c1d52926f',
    messagingSenderId: '701854077758',
    projectId: 'repasoflutterjunio',
    authDomain: 'repasoflutterjunio.firebaseapp.com',
    storageBucket: 'repasoflutterjunio.firebasestorage.app',
  );
}
